kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mood-night-pv-claim
  labels:
    app: back-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi