apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./mood-night-infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: vitaliisatanovskyi/mood-night-back
      context: mood-night-back
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: vitaliisatanovskyi/mood-night-client
      context: mood-night-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .