name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'mood-night-infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save moodnight
      - run: kubectl apply -f mood-night-infra/k8s && kubectl apply -f mood-night-infra/k8s-prod
