name: deploy-mood-night-back

on:
  push:
    branches:
      - master
    paths:
      - 'mood-night-back/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd mood-night-back && docker build -t vitaliisatanovskyi/mood-night-back .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push vitaliisatanovskyi/mood-night-back
