name: tests-mood-night-client

on:
  pull_request:
    paths:
      - 'mood-night-client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd mood-night-client && npm install && npm run test:ci
